# Generated by Django 4.2.13 on 2024-06-26 11:14

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
