"""
Django settings for stem project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
import environ


env = environ.Env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env.read_env(str(BASE_DIR / ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["*"])

# Application definition

INSTALLED_APPS = [
    'questions.apps.QuestionsConfig',
    'tests.apps.TestsConfig',
    'configuration.apps.ConfigurationConfig',
    'testView.apps.TestviewConfig',
    'question_bank.apps.QuestionBankConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'froala_editor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STATIC_ROOT = os.path.join(BASE_DIR, "static")


# Froala Editor settings
FROALA_EDITOR_THIRD_PARTY = ('image_aviary', 'spell_checker', 'wiris')
FROALA_EDITOR_PLUGINS = (
    'align', 'char_counter', 'code_beautifier', 'code_view', 'colors', 'draggable',
    'embedly', 'emoticons', 'entities', 'file', 'font_family', 'font_size', 'fullscreen',
    'image', 'image_manager', 'inline_style', 'line_breaker', 'link', 'lists',
    'paragraph_format', 'paragraph_style', 'quick_insert', 'quote', 'save', 'table',
    'url', 'video', 'wiris', 'special_characters', 'word_paste',
)

FROALA_EDITOR_OPTIONS = {
    'theme': 'gray',
    'lineBreakerOffset': 20,
    'imageUploadURL': 'https://restservices.oursite.org/api/File/UploadImage',
    'tableCellStyles': {
        'red': 'Red',
        'blue': 'Blue',
        'black': 'Black',
        'boldblack': 'Black and Bold',
        'extraboldblack': 'Extra bold and black',
        'center-bold': 'Centered and Bold'
    },
    'wordAllowedStyleProps': [
        'font-family', 'font-size', 'background', 'color', 'width', 'text-align', 'vertical-align',
        'background-color', 'padding', 'margin', 'height', 'margin-top', 'margin-left',
        'margin-right', 'margin-bottom', 'text-decoration', 'font-weight', 'font-style'
    ],
    'toolbarButtons': [
        'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|',
        'fontFamily', 'fontSize', 'colors', 'inlineStyle', 'paragraphStyle', '|',
        'wirisEditor', 'wirisChemistry', 'insertImage', 'insertTable', '-', 'insertLink', 'insertVideo', 'insertFile',
        'emoticons', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', '-',  'quote',
        'specialCharacters', 'insertHR', 'selectAll', 'clearFormatting', '|',
        'print', 'help', 'html', '|', 'undo', 'redo', '|'
    ],
    'word_paste': True,
    'htmlAllowedTags': ['.*'],  # Allow all HTML tags
    'htmlAllowedAttrs': ['.*'],  # Allow all HTML attributes
    'tableStyles': {
        'customTheme1': 'Custom Theme 1',
        'customTheme2': 'Custom Theme 2'
    }
}
