# Generated by Django 4.2.13 on 2024-07-05 13:32

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0003_question_answer_question_description_and_more'),
        ('tests', '0002_testsection_testtopic_remove_section_questions_and_more'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Enter duration in minutes')),
                ('publish_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('instructions', froala_editor.fields.FroalaField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.course')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testtype')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='TestViewSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewsubjects', to='testView.testview')),
            ],
            options={
                'verbose_name': 'TestView Subject',
                'verbose_name_plural': 'TestView Subjects',
            },
        ),
        migrations.CreateModel(
            name='TestViewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(related_name='viewsections', to='questions.question')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.strategy')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewsections', to='testView.testviewsubject')),
            ],
            options={
                'verbose_name': 'TestView Section',
                'verbose_name_plural': 'TestView Sections',
            },
        ),
    ]
