# Generated by Django 4.2.13 on 2024-07-05 10:41

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0003_question_answer_question_description_and_more'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('IBQ', 'IBQ')], max_length=50)),
                ('total_questions', models.IntegerField()),
                ('minimum_questions', models.IntegerField()),
                ('marks_per_question', models.FloatField()),
                ('negative_marks', models.FloatField(default=0)),
                ('instructions', models.TextField()),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('publish_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('instructions', froala_editor.fields.FroalaField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.course')),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tests.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testtype'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(related_name='sections', to='questions.question')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.strategy')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests.testsubject')),
            ],
        ),
    ]
