# Generated by Django 4.2.13 on 2024-07-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_answer_question_description_and_more'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.strategy')),
            ],
            options={
                'verbose_name': 'Test Section',
                'verbose_name_plural': 'Test Sections',
            },
        ),
        migrations.CreateModel(
            name='TestTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(related_name='sections', to='questions.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tests.testsection')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.RemoveField(
            model_name='section',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='section',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='section',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='testsubject',
            options={'verbose_name': 'Test Subject', 'verbose_name_plural': 'Test Subjects'},
        ),
        migrations.AlterModelOptions(
            name='testtype',
            options={'verbose_name': 'Test Type', 'verbose_name_plural': 'Test Types'},
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(help_text='Enter duration in minutes'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='testsection',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests.testsubject'),
        ),
    ]
